#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine

apt-get update
apt-get install -y nginx

printf "server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html;
    }

    location = / {
        return 200 'Hello World!\n';
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

}" > /etc/nginx/sites-available/default

service nginx restart

