#!/usr/bin/env bash
# Display listening sockets with PID and program name
tcp_sockets=$(ss -tlnp)
udp_sockets=$(ss -ulnp)
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
echo "$tcp_sockets"
echo "$udp_sockets"
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
echo "$(ss -lp | grep "unix")"
