#!/usr/bin/env bash

# Display header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps aux --forest --no-headers | awk '{printf "%-10s %5s %4s %4s %6s %5s %-8s %4s %7s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}'
