#!/usr/bin/env bash
# Function to handle SIGTERM signal

terminate() {
    echo "I am invincible!!!"
    exit
}
trap terminate SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
