#!/usr/bin/env bash
# This script displays the content of the current directory in a list format

for file in *; do
    if [ -f "$file" ] && [[ $file != .* ]]; then
        name_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_part"
    fi
done
