#!/usr/bin/env bash
# Backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/127.0.0.1 localhost.localdomain/127.0.0.2 localhost.localdomain/' /etc/hosts
sudo sed -i 's/127.0.1.1/127.0.0.1/' /etc/hosts
sudo sh -c 'echo "8.8.8.8 facebook.com" >> /etc/hosts'

service networking restart
